PREALERT_TEMPLATES = [
    "⏳ *JAY FX PRE-ALERT (00:00 UTC)*: Market scanning initiated! Our high-precision setup for *{pair}* dispatches in exactly 5 minutes. Prepare your terminals!",
    "⚡ *JAY FX PRE-ALERT (01:00 UTC)*: Volatility parameters locked. Get ready, the official trading signal for *{pair}* drops in 5 minutes!",
    "🎯 *JAY FX PRE-ALERT (02:00 UTC)*: Trend alignment confirmed. Position parameters for *{pair}* dispatching at 02:05 UTC. Stay alert!",
    "👑 *JAY FX PRE-ALERT (03:00 UTC)*: Asian session momentum building up! The upcoming setup for *{pair}* releases in 5 minutes.",
    "🛡️ *JAY FX PRE-ALERT (04:00 UTC)*: Risk parameters calculated. Our next high-probability setup on *{pair}* drops at 04:05 UTC!",
    "⏳ *JAY FX PRE-ALERT (05:00 UTC)*: Pre-market liquidity check completed. Signal for *{pair}* dispatching in 5 minutes!",
    "📈 *JAY FX PRE-ALERT (06:00 UTC)*: Early London pre-session check. Order execution zone for *{pair}* dispatches in 5 minutes!",
    "⚡ *JAY FX PRE-ALERT (07:00 UTC)*: London session open approaching! Get your MT4/MT5 ready, signal for *{pair}* drops at 07:05 UTC.",
    "👑 *JAY FX PRE-ALERT (08:00 UTC)*: High-probability setup detected. The upcoming trade for *{pair}* dispatches in 5 minutes!",
    "🎯 *JAY FX PRE-ALERT (09:00 UTC)*: Technical indicators aligned across 1H and 4H charts. *{pair}* setup releasing in 5 minutes!",
    "🛡️ *JAY FX PRE-ALERT (10:00 UTC)*: Institutional order flow scanning active. Signal for *{pair}* drops at 10:05 UTC. Get ready!",
    "⏳ *JAY FX PRE-ALERT (11:00 UTC)*: Mid-day momentum alert! Next setup for *{pair}* dispatches in 5 minutes. Trade wisely!",
    "⚡ *JAY FX PRE-ALERT (12:00 UTC)*: Pre-New York session check. Get set, official execution parameters for *{pair}* drop in 5 minutes!",
    "👑 *JAY FX PRE-ALERT (13:00 UTC)*: New York session overlapping! Major market liquidity active. *{pair}* signal releasing at 13:05 UTC.",
    "📈 *JAY FX PRE-ALERT (14:00 UTC)*: Peak New York volume detected. Our next high-conviction trade on *{pair}* dispatches in 5 minutes!",
    "🎯 *JAY FX PRE-ALERT (15:00 UTC)*: ATR volatility boundaries calculated. Setup for *{pair}* releases at 15:05 UTC. Stay tuned!",
    "🛡️ *JAY FX PRE-ALERT (16:00 UTC)*: Trend confirmation complete. The upcoming trade entry for *{pair}* drops in 5 minutes!",
    "⏳ *JAY FX PRE-ALERT (17:00 UTC)*: London session closing flow. High-precision execution for *{pair}* dispatches in 5 minutes!",
    "⚡ *JAY FX PRE-ALERT (18:00 UTC)*: Evening trade cycle initiated. Order parameters for *{pair}* drop at 18:05 UTC. Prepare your orders!",
    "👑 *JAY FX PRE-ALERT (19:00 UTC)*: Systematic market scan complete. The upcoming signal for *{pair}* releases in 5 minutes!",
    "🎯 *JAY FX PRE-ALERT (20:00 UTC)*: Late New York session flow. High-probability setup for *{pair}* dispatches at 20:05 UTC!",
    "🛡️ *JAY FX PRE-ALERT (21:00 UTC)*: Market rollover approaching. Volatility buffer active for *{pair}*. Signal drops in 5 minutes!",
    "⏳ *JAY FX PRE-ALERT (22:00 UTC)*: Overnight cycle active. Next technical trade entry on *{pair}* dispatches at 22:05 UTC!",
    "⚡ *JAY FX PRE-ALERT (23:00 UTC)*: Final trade cycle of the day! Get ready, signal for *{pair}* drops in 5 minutes."
]
